---
- name: Playbook that Sync the local repositories with Upstream.

  hosts: localhost
  vars:
    REMOTE: "{{ remote | default('upstream') }}"
    DIR_PATH: "{{ dir_path | default('thoth-station') }}"

  gather_facts: false
  connection: local
  tasks:
    - name: Fetching all the repositories from {{ DIR_PATH }}
      find:
        path: ~/{{ DIR_PATH }}
        file_type: directory
        recurse: no
      register: folders

    - set_fact:
        REPOS: "{{ folders.files | map(attribute='path') | list }}"

    - name: Update all the repositories from {{ DIR_PATH }}
      shell: |
        cd {{ item }}
        git checkout master
        git pull --rebase {{ REMOTE }} master
      with_items:
        - "{{ REPOS }}"
