#!/bin/sh
[ -n "$THOTH_NO_PRECOMMIT_TEST" ] && exit 0

which pipenv > /dev/null 2>&1 || {
	RED='\033[0;31m'
	NC='\033[0m'
	echo "${RED}Skipping the pre-commit test,as PIPENV is NOT installed${NC}"
	exit 0
}

pipenv run coala --non-interactive || exit 0
