apiVersion: v1
kind: Template
labels:
  template: core-e2e-test-buildconfig
  thoth: 0.1.0
metadata:
  name: core-e2e-test-buildconfig
  annotations:
    description: >
      This is Thoth Core End-to-End Test BuildConfig, this template is meant to be used by bots,
      but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: End-to-End Test BuildConfig'
    version: 0.1.0
    tags: poc,thoth,end-to-end,e2e,test,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Core End-to-End Test BuildConfig, this template is meant to be used by bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: core-e2e-test
    labels:
      app: thoth-core
      component: test
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "core-e2e-test:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
        env:
          - name: ENABLE_PIPENV
            value: '1'
          - name: UPGRADE_PIP_TO_LATEST
            value: ''
    triggers:
    - type: ImageChange
      imageChange: {}

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: core-e2e-test
    annotations:
      openshift.io/display-name: Thoth Core End-to-End Test
  spec:
    lookupPolicy:
      local: true
      
parameters:
- description: Name of the github repository for Thoth's User API
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/core'

- description: Git reference to be used for Thoth's User API
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
