apiVersion: v1
kind: Template
labels:
  template: thoth-core
  thoth: 0.1.0
metadata:
  name: thoth-core
  annotations:
    description: This is Thoth Core - common components 
    openshift.io/display-name: "Thoth Core: common components"
    version: 0.2.0
    tags: poc,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:

## Service Accounts
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: analyzer
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    app: thoth-core
  automountServiceAccountToken: true

- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: role-jobs-binding
    namespace: ${THOTH_MIDDLEEND_NAMESPACE}
    labels:
      app: thoth-core
  roleRef:
    kind: ClusterRole
    name: edit
  subjects:
    - kind: ServiceAccount
      name: analyzer
      namespace: ${THOTH_FRONTEND_NAMESPACE}

#
# Cron jobs
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: cleanup-job
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    labels:
      app: thoth-core
  spec:
    schedule: "@weekly"
    suspend: true
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: analyzer
            containers:
            - image: thoth-cleanup-job
              name: cleanup-cronjob
              env:
               - name: KUBERNETES_VERIFY_TLS
                 value: "0"
               - name: THOTH_ANALYZER_CLEANUP_TIME
                 valueFrom:
                  configMapKeyRef:
                    key: analyzer-cleanup-time
                    name: thoth
               - name: KUBERNETES_API_URL
                 value: 'https://kubernetes.default.svc.cluster.local'
               - name: THOTH_CLEANUP_DEBUG
                 valueFrom:
                  configMapKeyRef:
                    key: debug-cleanup
                    name: thoth
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "250m"
            restartPolicy: OnFailure

- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: graph-sync-job
    namespace: ${THOTH_BACKEND_NAMESPACE}
    labels:
      app: thoth-core
  spec:
    schedule: "@daily"
    suspend: true
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: thoth-graph-sync-job
              name: graph-sync-cronjob
              env:
              - name: THOTH_DEPLOYMENT_NAME
                valueFrom:
                  configMapKeyRef:
                    key: storage-bucket-name
                    name: thoth
              - name: THOTH_JANUSGRAPH_HOST
                value: janusgraph
              - name: THOTH_JANUSGRAPH_PORT
                value: '80'
              - name: THOTH_SYNC_OBSERVATIONS
                valueFrom:
                  configMapKeyRef:
                    key: sync-observations
                    name: thoth
              - name: THOTH_CEPH_HOST
                valueFrom:
                  configMapKeyRef:
                    key: ceph-host
                    name: thoth
              - name: THOTH_CEPH_BUCKET
                valueFrom:
                  configMapKeyRef:
                    key: ceph-bucket-name
                    name: thoth
              - name: THOTH_CEPH_BUCKET_PREFIX
                valueFrom:
                  configMapKeyRef:
                    key: ceph-bucket-prefix
                    name: thoth
              - name: THOTH_CEPH_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: thoth
                    key: ceph-key-id
              - name: THOTH_CEPH_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: thoth
                    key: ceph-secret-key
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
            restartPolicy: Never

#
# Image streams
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: python-36-centos7
    namespace: ${THOTH_BACKEND_NAMESPACE}
    annotations:
      openshift.io/display-name: Python
  spec:
    tags:
      - name: "latest"
        annotations:
          iconClass: icon-python
          supports: python:3.6,python
          version: "latest"
        from:
          kind: DockerImage
          name: docker.io/centos/python-36-centos7:latest

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: python-36-centos7
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    annotations:
      openshift.io/display-name: Python
  spec:
    tags:
      - name: "latest"
        annotations:
          iconClass: icon-python
          supports: python:3.6,python
          version: "latest"
        from:
          kind: DockerImage
          name: docker.io/centos/python-36-centos7:latest

parameters:
- description: Name of the Thoth Frontend Namespace
  displayName: Thoth Frontend Namespace
  required: true
  name: THOTH_FRONTEND_NAMESPACE

- description: Name of the Thoth Middle Tier Namespace
  displayName: Thoth Middle Tier Namespace
  required: true
  name: THOTH_MIDDLEEND_NAMESPACE

- description: Name of the Thoth Backend Namespace
  displayName: Thoth Backend Namespace
  required: true
  name: THOTH_BACKEND_NAMESPACE

- description: Time before analyzer pod gets removed from etcd.
  displayName: Thoth analyzer cleanup time
  required: true
  name: THOTH_ANALYZER_CLEANUP_TIME
  value: '7d'

- description: Be verbose in cluster cleanup job.
  displayName: Debug cleanup job
  required: true
  name: THOTH_CLEANUP_DEBUG
  value: '1'

- description: Turn on or off automatic observation syncing to the graph database.
  displayName: Sync observations
  required: true
  name: THOTH_SYNC_OBSERVATIONS
  value: '0'

- description: Storage bucket name to use for persisted files
  displayName: Thoth Storage bucket name
  required: true
  value: thoth-test
  name: THOTH_DEPLOYMENT_NAME
